### ISSUE TITLE
Нарушен порядок вызова функций.

### ISSUE THREAD

**Issue by bonvech** [C3mka21/MINI-FNAF#2]
Похоже, перепутан порядок вызовов функций вот в этом и подобном местах:
peter person::down()// движение вниз
{
    if(GetAsyncKeyState(s))
...
}
Сначала нужно проверить нажатие кнопки и только потом при необходимости вызвать функцию движения.

**Comment by C3mka21** [comment]
Исправил из-за нарушений логических действий
